description: 'Bad Request – Invalid input for creating a task.'
content:
  application/json:
    schema:
      type: object
      properties:
        status:
          type: integer
          example: 400
        message:
          type: string
          example: 'Board ID and Column ID are required'
