description: 'Unauthorized – User authentication failed.'
content:
  application/json:
    schema:
      type: object
      properties:
        status:
          type: integer
          example: 401
        message:
          type: string
          example: 'Unauthorized access. Please log in.'
