openapi: 3.1.0
info:
  version: 1.0.0
  title: Task Pro
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: App to save and interactive with tasks
tags:
  - name: Background
    description: Get background by name
  - name: Tasks
    description: Operations about tasks.
  - name: Auth
    description: Auth operations.
  - name: User
    description: Operations with user profile.
  - name: Support
    description: Support request via Email.
  - name: Board
    description: Operations with boards.

servers:
  - url: http://localhost:3000
  - url: https://task-pro-back-kri0.onrender.com
paths:
  /columns:
    post:
      $ref: ../swagger/paths/columns/post.yaml
  /columns/{id}:
    delete:
      $ref: ../swagger/paths/columns/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/columns/{id}/patch.yaml
  /tasks:
    post:
      $ref: ../swagger/paths/tasks/post.yaml
  /tasks/{taskId}:
    patch:
      $ref: ../swagger/paths/tasks/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/tasks/{id}/delete.yaml
  # /login:
  #   get:
  #     $ref:

  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register.yaml'
  /auth/current:
    get:
      $ref: '../swagger/paths/auth/current.yaml'
  /user:
    patch:
      $ref: ../swagger/paths/user/patch.yaml
  /support:
    post:
      $ref: ../swagger/paths/support/post.yaml
  /background/{name}:
    get:
      $ref: ../swagger/paths/background/background.yaml

  /board:
    get:
      $ref: ../swagger/paths/board/get.yaml
    post:
      $ref: ../swagger/paths/board/post.yaml
  /board/{id}:
    get:
      $ref: ../swagger/paths/board/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/board/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/board/{id}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
