post:
  summary: 'Create a new task'
  description: 'Creates a new task for the specified board and column.'
  tags:
    - 'Tasks'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            title:
              type: string
              example: 'Implement user authentication'
            content:
              type: string
              example: 'Create login and signup endpoints with JWT'
            priority:
              type: string
              enum: ['none', 'low', 'medium', 'high']
              example: 'high'
            deadline:
              type: string
              format: date-time
              example: '2024-12-31T23:59:59Z'
            boardId:
              type: string
              example: '64c5a4b2f2f9d20f8455b9b8'
            columnId:
              type: string
              example: '64c5a4b2f2f9d20f8455b9c9'
          required:
            - title
            - boardId
            - columnId
  responses:
    '201':
      description: 'Task created successfully'
      content:
        application/json:
          schema:
            type: object
            properties:
              task:
                $ref: '../../components/schemas/task.yaml'
    '400':
      description: 'Invalid input, Board ID and Column ID are required'
    '401':
      description: 'Unauthorized access'
